name: 🤔
on: [push]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: "MrBoolean/action-lerna@master"
        with:
          node-version: "10.x"  
      - run: lerna bootstrap
      - run: CI=true lerna run test
