name: 🤔
on: [push]

jobs:
    jest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - run: yarn
            - run: yarn lerna bootstrap
            - run: yarn lerna link
            - run: yarn lerna run build
            - run: CI=true yarn lerna run test --parallel
