name: 🕵‍♀
on: [push]

jobs:
    typescript:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: yarn
            - run: yarn add --dev @guardian/ab-core -W
            - run: yarn run link
            - run: yarn lerna run build
            - run: CI=true yarn lerna run tsc --parallel
